common/models/Settings.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "settings".
 *
 * @property string $name
 * @property string $data
 * @property int $status
 */
class Settings extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'settings';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'data'], 'required'],
            [['data'], 'string'],
            [['status'], 'integer'],
            [['name'], 'string', 'max' => 64],
            [['name'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'name' => 'Name',
            'data' => 'Data',
            'status' => 'Status',
        ];
    }
}

backend/controllers/SettingsController.php
<?php

namespace backend\controllers;

use backend\models\HeadersForm;
use backend\models\SocialsForm;
use frontend\components\Helpers;
use Yii;
use common\models\Settings;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SettingsController implements the CRUD actions for Settings model.
 */
class SettingsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Settings models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = Settings::find()->indexBy('name')->all();

        return $this->render('index', [
            'model' => $model
        ]);
    }

    public function actionSavesocial() {
        if (isset($_POST['SocialsForm'])) {
Helpers::pr($_POST);
            $check = true;
            $errors = array();
            foreach ($_POST['SocialsForm'] as $key => $val) {
                $model = new SocialsForm();
                $model->attributes = $val;
                if (!$model->validate()) {
                    $check = false;
                    $errors[$key] = $model->getErrors();
                }
            }
            if ($check) {
                Settings::updateAll(['data' => json_encode($_POST['SocialsForm'])], 'name = "socials"');
                echo json_encode(array());
            }
            else {
                echo json_encode($errors);
            }
        }
    }
    public function actionSaveHeaders() {
        if (isset($_POST['HeadersForm'])) {
            $check = true;
            $errors = array();
            foreach ($_POST['HeadersForm'] as $key => $val) {
                $model = new HeadersForm;
                $model->attributes = $val;
                if (!$model->validate()) {
                    $check = false;
                    $errors[$key] = $model->getErrors();
                }
            }
            if ($check) {
                Settings::updateAll(['data' => json_encode($_POST['HeadersForm'])], 'name = "headers"');
                echo json_encode(array());
            }
            else {
                echo json_encode($errors);
            }
        }
    }
}

backend/views/settings/_headers.php
<?php
/* @var $this \backend\controllers\SettingsController */
/* @var $form yii\widgets\ActiveForm */
/* @var $data \common\models\Settings */
$headers = json_decode($data->data, true);
$headers = $headers ? $headers : array();
?>

<div class="user-form box box-primary">
    <?php $form = \yii\widgets\ActiveForm::begin([
        'id' => 'header-form',
        'enableClientValidation'=>false
    ]); ?>
    <div class="box-body table-responsive">
        <?php foreach($headers as $s){
            $model = new \backend\models\HeadersForm();
            $model->attributes = $s;
            ?>
            <div class="header-module">
                <div class="clearfix">
                    <div class="col-sm-2">
                        <?= $form->field($model, 'position')->dropDownList([0 => 'Header', 1 => 'Footer']) ?>
                    </div>
                    <div class="col-sm-9">
                        <?= $form->field($model, 'code')->textarea(['rows' => '6']) ?>
                    </div>
                    <div class="col-sm-1">
                        <button class="btn btn-danger remove-header margin-top24"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
            </div>
        <?php } ?>
        <div class="clearfix">
            <div class="col-md-4 col-md-offset-4 margin-top">
                <button class="btn btn-warning btn-block add-header">Add Header</button>
            </div>
        </div>
    </div>

    <div class="box-footer">
        <?= \yii\helpers\Html::submitButton('Save', ['class' => 'btn btn-success btn-flat col-sm-12', 'id' => 'submit-button-header']) ?>
    </div>
    <?php \yii\widgets\ActiveForm::end(); ?>
</div>

<?php $model = new \backend\models\HeadersForm(); ?>
<div class="hidden">
    <div id="header_template">
        <div class="header-module">
            <div class="clearfix">
                <div class="col-sm-2">
                    <?= $form->field($model, 'position')->dropDownList([0 => 'Header', 1 => 'Footer']) ?>
                </div>
                <div class="col-sm-9">
                    <?= $form->field($model, 'code')->textarea(['rows' => '6']) ?>
                </div>
                <div class="col-sm-1">
                    <button class="btn btn-danger remove-header margin-top24"><i class="fa fa-remove"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> Success!</h4>
    Headers Networks Updated.
</div>
<script>
    $(document).ready(function () {
        $('.alert-success').hide();
        $(document).on('click', '.add-header', function (e) {
            e.preventDefault();
            $($('#header_template').html()).insertBefore($(this).closest('div.clearfix'));
        });
        $(document).on('click', '.remove-header', function (e) {
            e.preventDefault();
            $(this).closest('div.header-module').remove();
        });
        $(document).on('click', '#submit-button-header', function (e) {
            e.preventDefault();
            $.each($('.header-module'), function (k, v) {
                $.each($(this).find('input,textarea,select'), function () {
                    $(this).attr('name', $(this).attr('name').replace('[', '[' + k + ']['));
                });
            });

            $('#header-form div.error').remove();
            $.ajax({
                url: '<?=\yii\helpers\Url::to(['/settings/save-headers'])?>',
                type: 'post',
                data: $('#header-form').serializeArray(),
                dataType: 'json',
                success: function (data) {
                    $.each($('.header-module'), function (k, v) {
                        $.each($(this).find('input,textarea,select'), function () {
                            $(this).attr('name', $(this).attr('name').replace('[' + k + '][', '['));
                        });
                    });
                    if (data.length == 0) {
                        $('.header-module .required.has-error').removeClass('required has-error');
                        $('.header-module .help-block').html('');
                        $('.alert-success').fadeIn('slow').delay(800).fadeOut('slow');
                    } else {
                        $('.header-module .required.has-error').removeClass('required has-error');
                        $('.header-module .help-block').html('');
                        $.each(data, function (ke, va) {
                            $.each(va, function (k, v) {
                                $('.header-module:eq(' + (ke) + ') .field-headersform-' + k).addClass('required has-error');
                                $('.header-module:eq(' + (ke) + ') .field-headersform-' + k+ ' .help-block').html(v[0]);
                            });
                        });
                    }
                }
            });
        });
    });
</script>

backend/views/settings/_socials.php
<?php
/* @var $this \backend\controllers\SettingsController */
/* @var $form yii\widgets\ActiveForm */
/* @var $data \common\models\Settings */
$socials = json_decode($data->data, true);
$socials = $socials ? $socials : array();

?>

<div class="user-form box box-primary">
    <?php $form = \yii\widgets\ActiveForm::begin([
        'id' => 'social-form',
        'enableClientValidation'=>false
    ]); ?>
    <div class="box-body table-responsive">
        <?php foreach($socials as $s){
            $model = new \backend\models\SocialsForm();
            $model->attributes = $s;
            ?>
            <div class="social-module">
                <div class="clearfix">
                    <div class="col-sm-5">
                        <?= $form->field($model, 'url')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-sm-5">
                        <?= $form->field($model, 'icon')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-sm-1">
                        <?= $form->field($model, 'status')->checkbox(['class' => 'minimal']) ?>
                    </div>
                    <div class="col-sm-1">
                        <button class="btn btn-danger remove-social margin-top24"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
            </div>
        <?php } ?>
        <div class="clearfix">
            <div class="col-md-4 col-md-offset-4 margin-top">
                <button class="btn btn-warning btn-block add-social">Add Social</button>
            </div>
        </div>
    </div>

    <div class="box-footer">
        <?= \yii\helpers\Html::submitButton('Save', ['class' => 'btn btn-success btn-flat col-sm-12', 'id' => 'submit-button-social']) ?>
    </div>
    <?php \yii\widgets\ActiveForm::end(); ?>
</div>

<?php $model = new \backend\models\SocialsForm(); ?>
<div class="hidden">
    <div id="social_template">
        <div class="social-module">
            <div class="clearfix">
                <div class="col-sm-5">
                    <?= $form->field($model, 'url')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="col-sm-5">
                    <?= $form->field($model, 'icon')->textInput(['maxlength' => true]) ?>
                </div>
                <div class="col-sm-1">
                    <?= $form->field($model, 'status')->checkbox(['class' => 'minimal']) ?>
                </div>
                <div class="col-sm-1">
                    <button class="btn btn-danger remove-social margin-top24"><i class="fa fa-remove"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> Success!</h4>
    Social Networks Updated.
</div>
<script>
    $(document).ready(function () {
        $('.alert-success').hide();
        $(document).on('click', '.add-social', function (e) {
            e.preventDefault();
            $($('#social_template').html()).insertBefore($(this).closest('div.clearfix'));
        });
        $(document).on('click', '.remove-social', function (e) {
            e.preventDefault();
            $(this).closest('div.social-module').remove();
        });
        $(document).on('click', '#submit-button-social', function (e) {
            e.preventDefault();
            $.each($('.social-module'), function (k, v) {
                $.each($(this).find('input, select'), function () {
                    $(this).attr('name', $(this).attr('name').replace('[', '[' + k + ']['));
                });
            });

            $('#social-form div.error').remove();
            $.ajax({
                url: '<?=\yii\helpers\Url::to(['/settings/savesocial'])?>',
                type: 'post',
                data: $('#social-form').serializeArray(),
                dataType: 'json',
                success: function (data) {
                    $.each($('.social-module'), function (k, v) {
                        $.each($(this).find('input, select'), function () {
                            $(this).attr('name', $(this).attr('name').replace('[' + k + '][', '['));
                        });
                    });
                    if (data.length == 0) {
                        $('.social-module .required.has-error').removeClass('required has-error');
                        $('.social-module .help-block').html('');
                        $('.alert-success').fadeIn('slow').delay(800).fadeOut('slow');
                    } else {
                        $('.social-module .required.has-error').removeClass('required has-error');
                        $('.social-module .help-block').html('');
                        $.each(data, function (ke, va) {
                            $.each(va, function (k, v) {
                                $('.social-module:eq(' + (ke) + ') .field-socialsform-' + k).addClass('required has-error');
                                $('.social-module:eq(' + (ke) + ') .field-socialsform-' + k+ ' .help-block').html(v[0]);
                            });
                        });
                    }
                }
            });
        });
    });
</script>

backend/views/settings/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $this \backend\controllers\SettingsController */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Settings';
$this->params['breadcrumbs'][] = $this->title;
?>


<!-- Custom Tabs -->
<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Socials</a></li>
        <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">Headers</a></li>
        <li class=""><a href="#tab_3" data-toggle="tab" aria-expanded="false">Tab 3</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
            <?php echo $this->render('_socials', ['data' => $model['socials']]);?>
        </div>
        <div class="tab-pane" id="tab_2">
            <?php echo $this->render('_headers', ['data' => $model['headers']]);?>
        </div>
    </div>
    <!-- /.tab-content -->
</div>
<!-- nav-tabs-custom -->